apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_DATABASE: bW92aWVfZGI=  # base64 encoded value of movie_db
  MONGO_INITDB_ROOT_USERNAME: bXl1c2Vy  # base64 encoded value of myUsername
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=  # base64 encoded value of myPassword
